### ISSUE TITLE
Autoryzacja użytkownika

### ISSUE THREAD

**Issue by RorogRobert** [dkusmierek/symfony_migration_example#1]
Witaj

Czy jest jakiś prosty sposób aby przekazać autoryzację użytkownika do S1 jak mam go już zautoryzowanego w S5?

W szablonach S1 mam  wywołanie

`<?php $username = sfContext::getInstance()->getUser()->getGuardUser()->getName(); ?>`

oczywiście sfContext::getInstance()->getUser() zwraca null

**Comment by dkusmierek** [comment]
Cześć :) Jest na to sposób poprzez użycie klasy `sfBasicSecurityUser` z Symfony 1 i jej metody `initialize`. Generalnie trzeba zaimplementować translację sesji S5 -> S1 (najlepiej zrobić to w momencie logowania, a więc używając EventListenera). Następnie podczas inicjalizacji użytkownika S1, który dziedziczy po `sfBasicSecurityUser` odtworzyć tą sesję i wszystko będzie działać poprawnie. Jeśli będzie potrzeba postaram się to wytłumaczyć bardziej szczegółowo :)
